// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: ploto/user.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserCrudClient is the client API for UserCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCrudClient interface {
	Insert(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Users, error)
	Delete(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
}

type userCrudClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCrudClient(cc grpc.ClientConnInterface) UserCrudClient {
	return &userCrudClient{cc}
}

func (c *userCrudClient) Insert(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.v1.UserCrud/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCrudClient) Update(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.v1.UserCrud/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCrudClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/api.v1.UserCrud/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCrudClient) Delete(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.v1.UserCrud/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCrudServer is the server API for UserCrud service.
// All implementations must embed UnimplementedUserCrudServer
// for forward compatibility
type UserCrudServer interface {
	Insert(context.Context, *User) (*Response, error)
	Update(context.Context, *User) (*Response, error)
	List(context.Context, *ListRequest) (*Users, error)
	Delete(context.Context, *User) (*Response, error)
	mustEmbedUnimplementedUserCrudServer()
}

// UnimplementedUserCrudServer must be embedded to have forward compatible implementations.
type UnimplementedUserCrudServer struct {
}

func (UnimplementedUserCrudServer) Insert(context.Context, *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedUserCrudServer) Update(context.Context, *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserCrudServer) List(context.Context, *ListRequest) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedUserCrudServer) Delete(context.Context, *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserCrudServer) mustEmbedUnimplementedUserCrudServer() {}

// UnsafeUserCrudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCrudServer will
// result in compilation errors.
type UnsafeUserCrudServer interface {
	mustEmbedUnimplementedUserCrudServer()
}

func RegisterUserCrudServer(s grpc.ServiceRegistrar, srv UserCrudServer) {
	s.RegisterService(&UserCrud_ServiceDesc, srv)
}

func _UserCrud_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCrudServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.UserCrud/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCrudServer).Insert(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCrud_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCrudServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.UserCrud/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCrudServer).Update(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCrud_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCrudServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.UserCrud/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCrudServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCrud_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCrudServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.UserCrud/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCrudServer).Delete(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCrud_ServiceDesc is the grpc.ServiceDesc for UserCrud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCrud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.UserCrud",
	HandlerType: (*UserCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _UserCrud_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserCrud_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserCrud_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserCrud_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ploto/user.proto",
}
